# Generated by Django 5.0.4 on 2024-04-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('contactno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('emailaddress', models.EmailField(max_length=100)),
                ('dob', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=6)),
                ('address', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('zipcode', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('emailaddress', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=500)),
                ('message', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=30)),
                ('usertype', models.CharField(max_length=30)),
            ],
        ),
    ]
