# Generated by Django 5.0.4 on 2024-04-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('carid', models.AutoField(primary_key=True, serialize=False)),
                ('carname', models.CharField(max_length=100)),
                ('carno', models.CharField(max_length=50)),
                ('drivername', models.CharField(max_length=50)),
                ('carrent', models.IntegerField()),
                ('carpic', models.FileField(upload_to='')),
            ],
        ),
    ]
