# Generated by Django 5.0.4 on 2024-05-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinfo',
            name='availability',
            field=models.CharField(default='available', max_length=50),
            preserve_default=False,
        ),
    ]
