# Generated by Django 5.0.4 on 2024-05-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('bookedby', models.CharField(max_length=50)),
                ('contactno', models.CharField(max_length=10)),
                ('carname', models.CharField(max_length=100)),
                ('carno', models.CharField(max_length=50)),
                ('drivername', models.CharField(max_length=50)),
                ('carrent', models.IntegerField()),
                ('bookingdate', models.CharField(max_length=30)),
            ],
        ),
    ]
