# Generated by Django 5.0.4 on 2024-05-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='carid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
